package dev.uten2c.rainstom.block;

import net.minestom.server.sound.SoundEvent;
import org.jetbrains.annotations.NotNull;

/**
 * AUTOGENERATED by SoundTypeGenerator
 */
public enum SoundType {
    EMPTY(1.0f, 1.0f, "minecraft:intentionally_empty", "minecraft:intentionally_empty", "minecraft:intentionally_empty", "minecraft:intentionally_empty", "minecraft:intentionally_empty"),

    WOOD(1.0f, 1.0f, "minecraft:block.wood.break", "minecraft:block.wood.step", "minecraft:block.wood.place", "minecraft:block.wood.hit", "minecraft:block.wood.fall"),

    GRAVEL(1.0f, 1.0f, "minecraft:block.gravel.break", "minecraft:block.gravel.step", "minecraft:block.gravel.place", "minecraft:block.gravel.hit", "minecraft:block.gravel.fall"),

    GRASS(1.0f, 1.0f, "minecraft:block.grass.break", "minecraft:block.grass.step", "minecraft:block.grass.place", "minecraft:block.grass.hit", "minecraft:block.grass.fall"),

    LILY_PAD(1.0f, 1.0f, "minecraft:block.big_dripleaf.break", "minecraft:block.big_dripleaf.step", "minecraft:block.lily_pad.place", "minecraft:block.big_dripleaf.hit", "minecraft:block.big_dripleaf.fall"),

    STONE(1.0f, 1.0f, "minecraft:block.stone.break", "minecraft:block.stone.step", "minecraft:block.stone.place", "minecraft:block.stone.hit", "minecraft:block.stone.fall"),

    METAL(1.0f, 1.5f, "minecraft:block.metal.break", "minecraft:block.metal.step", "minecraft:block.metal.place", "minecraft:block.metal.hit", "minecraft:block.metal.fall"),

    GLASS(1.0f, 1.0f, "minecraft:block.glass.break", "minecraft:block.glass.step", "minecraft:block.glass.place", "minecraft:block.glass.hit", "minecraft:block.glass.fall"),

    WOOL(1.0f, 1.0f, "minecraft:block.wool.break", "minecraft:block.wool.step", "minecraft:block.wool.place", "minecraft:block.wool.hit", "minecraft:block.wool.fall"),

    SAND(1.0f, 1.0f, "minecraft:block.sand.break", "minecraft:block.sand.step", "minecraft:block.sand.place", "minecraft:block.sand.hit", "minecraft:block.sand.fall"),

    SNOW(1.0f, 1.0f, "minecraft:block.snow.break", "minecraft:block.snow.step", "minecraft:block.snow.place", "minecraft:block.snow.hit", "minecraft:block.snow.fall"),

    POWDER_SNOW(1.0f, 1.0f, "minecraft:block.powder_snow.break", "minecraft:block.powder_snow.step", "minecraft:block.powder_snow.place", "minecraft:block.powder_snow.hit", "minecraft:block.powder_snow.fall"),

    LADDER(1.0f, 1.0f, "minecraft:block.ladder.break", "minecraft:block.ladder.step", "minecraft:block.ladder.place", "minecraft:block.ladder.hit", "minecraft:block.ladder.fall"),

    ANVIL(0.3f, 1.0f, "minecraft:block.anvil.break", "minecraft:block.anvil.step", "minecraft:block.anvil.place", "minecraft:block.anvil.hit", "minecraft:block.anvil.fall"),

    SLIME_BLOCK(1.0f, 1.0f, "minecraft:block.slime_block.break", "minecraft:block.slime_block.step", "minecraft:block.slime_block.place", "minecraft:block.slime_block.hit", "minecraft:block.slime_block.fall"),

    HONEY_BLOCK(1.0f, 1.0f, "minecraft:block.honey_block.break", "minecraft:block.honey_block.step", "minecraft:block.honey_block.place", "minecraft:block.honey_block.hit", "minecraft:block.honey_block.fall"),

    WET_GRASS(1.0f, 1.0f, "minecraft:block.wet_grass.break", "minecraft:block.wet_grass.step", "minecraft:block.wet_grass.place", "minecraft:block.wet_grass.hit", "minecraft:block.wet_grass.fall"),

    CORAL_BLOCK(1.0f, 1.0f, "minecraft:block.coral_block.break", "minecraft:block.coral_block.step", "minecraft:block.coral_block.place", "minecraft:block.coral_block.hit", "minecraft:block.coral_block.fall"),

    BAMBOO(1.0f, 1.0f, "minecraft:block.bamboo.break", "minecraft:block.bamboo.step", "minecraft:block.bamboo.place", "minecraft:block.bamboo.hit", "minecraft:block.bamboo.fall"),

    BAMBOO_SAPLING(1.0f, 1.0f, "minecraft:block.bamboo_sapling.break", "minecraft:block.bamboo.step", "minecraft:block.bamboo_sapling.place", "minecraft:block.bamboo_sapling.hit", "minecraft:block.bamboo.fall"),

    SCAFFOLDING(1.0f, 1.0f, "minecraft:block.scaffolding.break", "minecraft:block.scaffolding.step", "minecraft:block.scaffolding.place", "minecraft:block.scaffolding.hit", "minecraft:block.scaffolding.fall"),

    SWEET_BERRY_BUSH(1.0f, 1.0f, "minecraft:block.sweet_berry_bush.break", "minecraft:block.grass.step", "minecraft:block.sweet_berry_bush.place", "minecraft:block.grass.hit", "minecraft:block.grass.fall"),

    CROP(1.0f, 1.0f, "minecraft:block.crop.break", "minecraft:block.grass.step", "minecraft:item.crop.plant", "minecraft:block.grass.hit", "minecraft:block.grass.fall"),

    HARD_CROP(1.0f, 1.0f, "minecraft:block.wood.break", "minecraft:block.wood.step", "minecraft:item.crop.plant", "minecraft:block.wood.hit", "minecraft:block.wood.fall"),

    VINE(1.0f, 1.0f, "minecraft:block.vine.break", "minecraft:block.vine.step", "minecraft:block.vine.place", "minecraft:block.vine.hit", "minecraft:block.vine.fall"),

    NETHER_WART(1.0f, 1.0f, "minecraft:block.nether_wart.break", "minecraft:block.stone.step", "minecraft:item.nether_wart.plant", "minecraft:block.stone.hit", "minecraft:block.stone.fall"),

    LANTERN(1.0f, 1.0f, "minecraft:block.lantern.break", "minecraft:block.lantern.step", "minecraft:block.lantern.place", "minecraft:block.lantern.hit", "minecraft:block.lantern.fall"),

    STEM(1.0f, 1.0f, "minecraft:block.stem.break", "minecraft:block.stem.step", "minecraft:block.stem.place", "minecraft:block.stem.hit", "minecraft:block.stem.fall"),

    NYLIUM(1.0f, 1.0f, "minecraft:block.nylium.break", "minecraft:block.nylium.step", "minecraft:block.nylium.place", "minecraft:block.nylium.hit", "minecraft:block.nylium.fall"),

    FUNGUS(1.0f, 1.0f, "minecraft:block.fungus.break", "minecraft:block.fungus.step", "minecraft:block.fungus.place", "minecraft:block.fungus.hit", "minecraft:block.fungus.fall"),

    ROOTS(1.0f, 1.0f, "minecraft:block.roots.break", "minecraft:block.roots.step", "minecraft:block.roots.place", "minecraft:block.roots.hit", "minecraft:block.roots.fall"),

    SHROOMLIGHT(1.0f, 1.0f, "minecraft:block.shroomlight.break", "minecraft:block.shroomlight.step", "minecraft:block.shroomlight.place", "minecraft:block.shroomlight.hit", "minecraft:block.shroomlight.fall"),

    WEEPING_VINES(1.0f, 1.0f, "minecraft:block.weeping_vines.break", "minecraft:block.weeping_vines.step", "minecraft:block.weeping_vines.place", "minecraft:block.weeping_vines.hit", "minecraft:block.weeping_vines.fall"),

    TWISTING_VINES(1.0f, 0.5f, "minecraft:block.weeping_vines.break", "minecraft:block.weeping_vines.step", "minecraft:block.weeping_vines.place", "minecraft:block.weeping_vines.hit", "minecraft:block.weeping_vines.fall"),

    SOUL_SAND(1.0f, 1.0f, "minecraft:block.soul_sand.break", "minecraft:block.soul_sand.step", "minecraft:block.soul_sand.place", "minecraft:block.soul_sand.hit", "minecraft:block.soul_sand.fall"),

    SOUL_SOIL(1.0f, 1.0f, "minecraft:block.soul_soil.break", "minecraft:block.soul_soil.step", "minecraft:block.soul_soil.place", "minecraft:block.soul_soil.hit", "minecraft:block.soul_soil.fall"),

    BASALT(1.0f, 1.0f, "minecraft:block.basalt.break", "minecraft:block.basalt.step", "minecraft:block.basalt.place", "minecraft:block.basalt.hit", "minecraft:block.basalt.fall"),

    WART_BLOCK(1.0f, 1.0f, "minecraft:block.wart_block.break", "minecraft:block.wart_block.step", "minecraft:block.wart_block.place", "minecraft:block.wart_block.hit", "minecraft:block.wart_block.fall"),

    NETHERRACK(1.0f, 1.0f, "minecraft:block.netherrack.break", "minecraft:block.netherrack.step", "minecraft:block.netherrack.place", "minecraft:block.netherrack.hit", "minecraft:block.netherrack.fall"),

    NETHER_BRICKS(1.0f, 1.0f, "minecraft:block.nether_bricks.break", "minecraft:block.nether_bricks.step", "minecraft:block.nether_bricks.place", "minecraft:block.nether_bricks.hit", "minecraft:block.nether_bricks.fall"),

    NETHER_SPROUTS(1.0f, 1.0f, "minecraft:block.nether_sprouts.break", "minecraft:block.nether_sprouts.step", "minecraft:block.nether_sprouts.place", "minecraft:block.nether_sprouts.hit", "minecraft:block.nether_sprouts.fall"),

    NETHER_ORE(1.0f, 1.0f, "minecraft:block.nether_ore.break", "minecraft:block.nether_ore.step", "minecraft:block.nether_ore.place", "minecraft:block.nether_ore.hit", "minecraft:block.nether_ore.fall"),

    BONE_BLOCK(1.0f, 1.0f, "minecraft:block.bone_block.break", "minecraft:block.bone_block.step", "minecraft:block.bone_block.place", "minecraft:block.bone_block.hit", "minecraft:block.bone_block.fall"),

    NETHERITE_BLOCK(1.0f, 1.0f, "minecraft:block.netherite_block.break", "minecraft:block.netherite_block.step", "minecraft:block.netherite_block.place", "minecraft:block.netherite_block.hit", "minecraft:block.netherite_block.fall"),

    ANCIENT_DEBRIS(1.0f, 1.0f, "minecraft:block.ancient_debris.break", "minecraft:block.ancient_debris.step", "minecraft:block.ancient_debris.place", "minecraft:block.ancient_debris.hit", "minecraft:block.ancient_debris.fall"),

    LODESTONE(1.0f, 1.0f, "minecraft:block.lodestone.break", "minecraft:block.lodestone.step", "minecraft:block.lodestone.place", "minecraft:block.lodestone.hit", "minecraft:block.lodestone.fall"),

    CHAIN(1.0f, 1.0f, "minecraft:block.chain.break", "minecraft:block.chain.step", "minecraft:block.chain.place", "minecraft:block.chain.hit", "minecraft:block.chain.fall"),

    NETHER_GOLD_ORE(1.0f, 1.0f, "minecraft:block.nether_gold_ore.break", "minecraft:block.nether_gold_ore.step", "minecraft:block.nether_gold_ore.place", "minecraft:block.nether_gold_ore.hit", "minecraft:block.nether_gold_ore.fall"),

    GILDED_BLACKSTONE(1.0f, 1.0f, "minecraft:block.gilded_blackstone.break", "minecraft:block.gilded_blackstone.step", "minecraft:block.gilded_blackstone.place", "minecraft:block.gilded_blackstone.hit", "minecraft:block.gilded_blackstone.fall"),

    CANDLE(1.0f, 1.0f, "minecraft:block.candle.break", "minecraft:block.candle.step", "minecraft:block.candle.place", "minecraft:block.candle.hit", "minecraft:block.candle.fall"),

    AMETHYST(1.0f, 1.0f, "minecraft:block.amethyst_block.break", "minecraft:block.amethyst_block.step", "minecraft:block.amethyst_block.place", "minecraft:block.amethyst_block.hit", "minecraft:block.amethyst_block.fall"),

    AMETHYST_CLUSTER(1.0f, 1.0f, "minecraft:block.amethyst_cluster.break", "minecraft:block.amethyst_cluster.step", "minecraft:block.amethyst_cluster.place", "minecraft:block.amethyst_cluster.hit", "minecraft:block.amethyst_cluster.fall"),

    SMALL_AMETHYST_BUD(1.0f, 1.0f, "minecraft:block.small_amethyst_bud.break", "minecraft:block.amethyst_cluster.step", "minecraft:block.small_amethyst_bud.place", "minecraft:block.amethyst_cluster.hit", "minecraft:block.amethyst_cluster.fall"),

    MEDIUM_AMETHYST_BUD(1.0f, 1.0f, "minecraft:block.medium_amethyst_bud.break", "minecraft:block.amethyst_cluster.step", "minecraft:block.medium_amethyst_bud.place", "minecraft:block.amethyst_cluster.hit", "minecraft:block.amethyst_cluster.fall"),

    LARGE_AMETHYST_BUD(1.0f, 1.0f, "minecraft:block.large_amethyst_bud.break", "minecraft:block.amethyst_cluster.step", "minecraft:block.large_amethyst_bud.place", "minecraft:block.amethyst_cluster.hit", "minecraft:block.amethyst_cluster.fall"),

    TUFF(1.0f, 1.0f, "minecraft:block.tuff.break", "minecraft:block.tuff.step", "minecraft:block.tuff.place", "minecraft:block.tuff.hit", "minecraft:block.tuff.fall"),

    CALCITE(1.0f, 1.0f, "minecraft:block.calcite.break", "minecraft:block.calcite.step", "minecraft:block.calcite.place", "minecraft:block.calcite.hit", "minecraft:block.calcite.fall"),

    DRIPSTONE_BLOCK(1.0f, 1.0f, "minecraft:block.dripstone_block.break", "minecraft:block.dripstone_block.step", "minecraft:block.dripstone_block.place", "minecraft:block.dripstone_block.hit", "minecraft:block.dripstone_block.fall"),

    POINTED_DRIPSTONE(1.0f, 1.0f, "minecraft:block.pointed_dripstone.break", "minecraft:block.pointed_dripstone.step", "minecraft:block.pointed_dripstone.place", "minecraft:block.pointed_dripstone.hit", "minecraft:block.pointed_dripstone.fall"),

    COPPER(1.0f, 1.0f, "minecraft:block.copper.break", "minecraft:block.copper.step", "minecraft:block.copper.place", "minecraft:block.copper.hit", "minecraft:block.copper.fall"),

    CAVE_VINES(1.0f, 1.0f, "minecraft:block.cave_vines.break", "minecraft:block.cave_vines.step", "minecraft:block.cave_vines.place", "minecraft:block.cave_vines.hit", "minecraft:block.cave_vines.fall"),

    SPORE_BLOSSOM(1.0f, 1.0f, "minecraft:block.spore_blossom.break", "minecraft:block.spore_blossom.step", "minecraft:block.spore_blossom.place", "minecraft:block.spore_blossom.hit", "minecraft:block.spore_blossom.fall"),

    AZALEA(1.0f, 1.0f, "minecraft:block.azalea.break", "minecraft:block.azalea.step", "minecraft:block.azalea.place", "minecraft:block.azalea.hit", "minecraft:block.azalea.fall"),

    FLOWERING_AZALEA(1.0f, 1.0f, "minecraft:block.flowering_azalea.break", "minecraft:block.flowering_azalea.step", "minecraft:block.flowering_azalea.place", "minecraft:block.flowering_azalea.hit", "minecraft:block.flowering_azalea.fall"),

    MOSS_CARPET(1.0f, 1.0f, "minecraft:block.moss_carpet.break", "minecraft:block.moss_carpet.step", "minecraft:block.moss_carpet.place", "minecraft:block.moss_carpet.hit", "minecraft:block.moss_carpet.fall"),

    PINK_PETALS(1.0f, 1.0f, "minecraft:block.pink_petals.break", "minecraft:block.pink_petals.step", "minecraft:block.pink_petals.place", "minecraft:block.pink_petals.hit", "minecraft:block.pink_petals.fall"),

    MOSS(1.0f, 1.0f, "minecraft:block.moss.break", "minecraft:block.moss.step", "minecraft:block.moss.place", "minecraft:block.moss.hit", "minecraft:block.moss.fall"),

    BIG_DRIPLEAF(1.0f, 1.0f, "minecraft:block.big_dripleaf.break", "minecraft:block.big_dripleaf.step", "minecraft:block.big_dripleaf.place", "minecraft:block.big_dripleaf.hit", "minecraft:block.big_dripleaf.fall"),

    SMALL_DRIPLEAF(1.0f, 1.0f, "minecraft:block.small_dripleaf.break", "minecraft:block.small_dripleaf.step", "minecraft:block.small_dripleaf.place", "minecraft:block.small_dripleaf.hit", "minecraft:block.small_dripleaf.fall"),

    ROOTED_DIRT(1.0f, 1.0f, "minecraft:block.rooted_dirt.break", "minecraft:block.rooted_dirt.step", "minecraft:block.rooted_dirt.place", "minecraft:block.rooted_dirt.hit", "minecraft:block.rooted_dirt.fall"),

    HANGING_ROOTS(1.0f, 1.0f, "minecraft:block.hanging_roots.break", "minecraft:block.hanging_roots.step", "minecraft:block.hanging_roots.place", "minecraft:block.hanging_roots.hit", "minecraft:block.hanging_roots.fall"),

    AZALEA_LEAVES(1.0f, 1.0f, "minecraft:block.azalea_leaves.break", "minecraft:block.azalea_leaves.step", "minecraft:block.azalea_leaves.place", "minecraft:block.azalea_leaves.hit", "minecraft:block.azalea_leaves.fall"),

    SCULK_SENSOR(1.0f, 1.0f, "minecraft:block.sculk_sensor.break", "minecraft:block.sculk_sensor.step", "minecraft:block.sculk_sensor.place", "minecraft:block.sculk_sensor.hit", "minecraft:block.sculk_sensor.fall"),

    SCULK_CATALYST(1.0f, 1.0f, "minecraft:block.sculk_catalyst.break", "minecraft:block.sculk_catalyst.step", "minecraft:block.sculk_catalyst.place", "minecraft:block.sculk_catalyst.hit", "minecraft:block.sculk_catalyst.fall"),

    SCULK(1.0f, 1.0f, "minecraft:block.sculk.break", "minecraft:block.sculk.step", "minecraft:block.sculk.place", "minecraft:block.sculk.hit", "minecraft:block.sculk.fall"),

    SCULK_VEIN(1.0f, 1.0f, "minecraft:block.sculk_vein.break", "minecraft:block.sculk_vein.step", "minecraft:block.sculk_vein.place", "minecraft:block.sculk_vein.hit", "minecraft:block.sculk_vein.fall"),

    SCULK_SHRIEKER(1.0f, 1.0f, "minecraft:block.sculk_shrieker.break", "minecraft:block.sculk_shrieker.step", "minecraft:block.sculk_shrieker.place", "minecraft:block.sculk_shrieker.hit", "minecraft:block.sculk_shrieker.fall"),

    GLOW_LICHEN(1.0f, 1.0f, "minecraft:block.grass.break", "minecraft:block.vine.step", "minecraft:block.grass.place", "minecraft:block.grass.hit", "minecraft:block.grass.fall"),

    DEEPSLATE(1.0f, 1.0f, "minecraft:block.deepslate.break", "minecraft:block.deepslate.step", "minecraft:block.deepslate.place", "minecraft:block.deepslate.hit", "minecraft:block.deepslate.fall"),

    DEEPSLATE_BRICKS(1.0f, 1.0f, "minecraft:block.deepslate_bricks.break", "minecraft:block.deepslate_bricks.step", "minecraft:block.deepslate_bricks.place", "minecraft:block.deepslate_bricks.hit", "minecraft:block.deepslate_bricks.fall"),

    DEEPSLATE_TILES(1.0f, 1.0f, "minecraft:block.deepslate_tiles.break", "minecraft:block.deepslate_tiles.step", "minecraft:block.deepslate_tiles.place", "minecraft:block.deepslate_tiles.hit", "minecraft:block.deepslate_tiles.fall"),

    POLISHED_DEEPSLATE(1.0f, 1.0f, "minecraft:block.polished_deepslate.break", "minecraft:block.polished_deepslate.step", "minecraft:block.polished_deepslate.place", "minecraft:block.polished_deepslate.hit", "minecraft:block.polished_deepslate.fall"),

    FROGLIGHT(1.0f, 1.0f, "minecraft:block.froglight.break", "minecraft:block.froglight.step", "minecraft:block.froglight.place", "minecraft:block.froglight.hit", "minecraft:block.froglight.fall"),

    FROGSPAWN(1.0f, 1.0f, "minecraft:block.frogspawn.break", "minecraft:block.frogspawn.step", "minecraft:block.frogspawn.place", "minecraft:block.frogspawn.hit", "minecraft:block.frogspawn.fall"),

    MANGROVE_ROOTS(1.0f, 1.0f, "minecraft:block.mangrove_roots.break", "minecraft:block.mangrove_roots.step", "minecraft:block.mangrove_roots.place", "minecraft:block.mangrove_roots.hit", "minecraft:block.mangrove_roots.fall"),

    MUDDY_MANGROVE_ROOTS(1.0f, 1.0f, "minecraft:block.muddy_mangrove_roots.break", "minecraft:block.muddy_mangrove_roots.step", "minecraft:block.muddy_mangrove_roots.place", "minecraft:block.muddy_mangrove_roots.hit", "minecraft:block.muddy_mangrove_roots.fall"),

    MUD(1.0f, 1.0f, "minecraft:block.mud.break", "minecraft:block.mud.step", "minecraft:block.mud.place", "minecraft:block.mud.hit", "minecraft:block.mud.fall"),

    MUD_BRICKS(1.0f, 1.0f, "minecraft:block.mud_bricks.break", "minecraft:block.mud_bricks.step", "minecraft:block.mud_bricks.place", "minecraft:block.mud_bricks.hit", "minecraft:block.mud_bricks.fall"),

    PACKED_MUD(1.0f, 1.0f, "minecraft:block.packed_mud.break", "minecraft:block.packed_mud.step", "minecraft:block.packed_mud.place", "minecraft:block.packed_mud.hit", "minecraft:block.packed_mud.fall"),

    HANGING_SIGN(1.0f, 1.0f, "minecraft:block.hanging_sign.break", "minecraft:block.hanging_sign.step", "minecraft:block.hanging_sign.place", "minecraft:block.hanging_sign.hit", "minecraft:block.hanging_sign.fall"),

    NETHER_WOOD_HANGING_SIGN(1.0f, 1.0f, "minecraft:block.nether_wood_hanging_sign.break", "minecraft:block.nether_wood_hanging_sign.step", "minecraft:block.nether_wood_hanging_sign.place", "minecraft:block.nether_wood_hanging_sign.hit", "minecraft:block.nether_wood_hanging_sign.fall"),

    BAMBOO_WOOD_HANGING_SIGN(1.0f, 1.0f, "minecraft:block.bamboo_wood_hanging_sign.break", "minecraft:block.bamboo_wood_hanging_sign.step", "minecraft:block.bamboo_wood_hanging_sign.place", "minecraft:block.bamboo_wood_hanging_sign.hit", "minecraft:block.bamboo_wood_hanging_sign.fall"),

    BAMBOO_WOOD(1.0f, 1.0f, "minecraft:block.bamboo_wood.break", "minecraft:block.bamboo_wood.step", "minecraft:block.bamboo_wood.place", "minecraft:block.bamboo_wood.hit", "minecraft:block.bamboo_wood.fall"),

    NETHER_WOOD(1.0f, 1.0f, "minecraft:block.nether_wood.break", "minecraft:block.nether_wood.step", "minecraft:block.nether_wood.place", "minecraft:block.nether_wood.hit", "minecraft:block.nether_wood.fall"),

    CHERRY_WOOD(1.0f, 1.0f, "minecraft:block.cherry_wood.break", "minecraft:block.cherry_wood.step", "minecraft:block.cherry_wood.place", "minecraft:block.cherry_wood.hit", "minecraft:block.cherry_wood.fall"),

    CHERRY_SAPLING(1.0f, 1.0f, "minecraft:block.cherry_sapling.break", "minecraft:block.cherry_sapling.step", "minecraft:block.cherry_sapling.place", "minecraft:block.cherry_sapling.hit", "minecraft:block.cherry_sapling.fall"),

    CHERRY_LEAVES(1.0f, 1.0f, "minecraft:block.cherry_leaves.break", "minecraft:block.cherry_leaves.step", "minecraft:block.cherry_leaves.place", "minecraft:block.cherry_leaves.hit", "minecraft:block.cherry_leaves.fall"),

    CHERRY_WOOD_HANGING_SIGN(1.0f, 1.0f, "minecraft:block.cherry_wood_hanging_sign.break", "minecraft:block.cherry_wood_hanging_sign.step", "minecraft:block.cherry_wood_hanging_sign.place", "minecraft:block.cherry_wood_hanging_sign.hit", "minecraft:block.cherry_wood_hanging_sign.fall"),

    CHISELED_BOOKSHELF(1.0f, 1.0f, "minecraft:block.chiseled_bookshelf.break", "minecraft:block.chiseled_bookshelf.step", "minecraft:block.chiseled_bookshelf.place", "minecraft:block.chiseled_bookshelf.hit", "minecraft:block.chiseled_bookshelf.fall"),

    SUSPICIOUS_SAND(1.0f, 1.0f, "minecraft:block.suspicious_sand.break", "minecraft:block.suspicious_sand.step", "minecraft:block.suspicious_sand.place", "minecraft:block.suspicious_sand.hit", "minecraft:block.suspicious_sand.fall"),

    SUSPICIOUS_GRAVEL(1.0f, 1.0f, "minecraft:block.suspicious_gravel.break", "minecraft:block.suspicious_gravel.step", "minecraft:block.suspicious_gravel.place", "minecraft:block.suspicious_gravel.hit", "minecraft:block.suspicious_gravel.fall"),

    DECORATED_POT(1.0f, 1.0f, "minecraft:block.decorated_pot.break", "minecraft:block.decorated_pot.step", "minecraft:block.decorated_pot.place", "minecraft:block.decorated_pot.hit", "minecraft:block.decorated_pot.fall"),

    DECORATED_POT_CRACKED(1.0f, 1.0f, "minecraft:block.decorated_pot.shatter", "minecraft:block.decorated_pot.step", "minecraft:block.decorated_pot.place", "minecraft:block.decorated_pot.hit", "minecraft:block.decorated_pot.fall");

    private final float volume;

    private final float pitch;

    private final SoundEvent breakSound;

    private final SoundEvent stepSound;

    private final SoundEvent placeSound;

    private final SoundEvent hitSound;

    private final SoundEvent fallSound;

    SoundType(float volume, float pitch, @NotNull String breakSound, @NotNull String stepSound,
            @NotNull String placeSound, @NotNull String hitSound, @NotNull String fallSound) {
        this.volume = volume;
        this.pitch = pitch;
        this.breakSound = SoundEvent.fromNamespaceId(breakSound);
        this.stepSound = SoundEvent.fromNamespaceId(stepSound);
        this.placeSound = SoundEvent.fromNamespaceId(placeSound);
        this.hitSound = SoundEvent.fromNamespaceId(hitSound);
        this.fallSound = SoundEvent.fromNamespaceId(fallSound);
    }

    public float getVolume() {
        return this.volume;
    }

    public float getPitch() {
        return this.pitch;
    }

    public @NotNull SoundEvent getBreakSound() {
        return this.breakSound;
    }

    public @NotNull SoundEvent getStepSound() {
        return this.stepSound;
    }

    public @NotNull SoundEvent getPlaceSound() {
        return this.placeSound;
    }

    public @NotNull SoundEvent getHitSound() {
        return this.hitSound;
    }

    public @NotNull SoundEvent getFallSound() {
        return this.fallSound;
    }
}
