package dev.uten2c.wagasa.damage;

import net.minestom.server.utils.NamespaceID;
import org.jetbrains.annotations.NotNull;

import java.util.Arrays;
import java.util.List;

/**
 * AUTOGENERATED by DamageTypeGenerator
 */
@SuppressWarnings("unused")
public final class VanillaDamageTypes {
    @NotNull
    public static final VanillaDamageType WITHER = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:wither"))
            .messageId("wither")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType SONIC_BOOM = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:sonic_boom"))
            .messageId("sonic_boom")
            .scaling(DamageScaling.ALWAYS)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType WITHER_SKULL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:wither_skull"))
            .messageId("witherSkull")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType DRY_OUT = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:dry_out"))
            .messageId("dryout")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType TRIDENT = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:trident"))
            .messageId("trident")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType ON_FIRE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:on_fire"))
            .messageId("onFire")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType FALL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:fall"))
            .messageId("fall")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .deathMessageType(DeathMessageType.FALL_VARIANTS)
            .build();

    @NotNull
    public static final VanillaDamageType MOB_ATTACK = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:mob_attack"))
            .messageId("mob")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType MOB_PROJECTILE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:mob_projectile"))
            .messageId("mob")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType THROWN = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:thrown"))
            .messageId("thrown")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType FALLING_STALACTITE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:falling_stalactite"))
            .messageId("fallingStalactite")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType FIREBALL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:fireball"))
            .messageId("fireball")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType FALLING_BLOCK = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:falling_block"))
            .messageId("fallingBlock")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType PLAYER_EXPLOSION = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:player_explosion"))
            .messageId("explosion.player")
            .scaling(DamageScaling.ALWAYS)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType STING = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:sting"))
            .messageId("sting")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType UNATTRIBUTED_FIREBALL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:unattributed_fireball"))
            .messageId("onFire")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType IN_WALL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:in_wall"))
            .messageId("inWall")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType IN_FIRE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:in_fire"))
            .messageId("inFire")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType ARROW = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:arrow"))
            .messageId("arrow")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType HOT_FLOOR = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:hot_floor"))
            .messageId("hotFloor")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType DROWN = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:drown"))
            .messageId("drown")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .effects(DamageEffects.DROWNING)
            .build();

    @NotNull
    public static final VanillaDamageType STARVE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:starve"))
            .messageId("starve")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType DRAGON_BREATH = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:dragon_breath"))
            .messageId("dragonBreath")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType MOB_ATTACK_NO_AGGRO = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:mob_attack_no_aggro"))
            .messageId("mob")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType LAVA = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:lava"))
            .messageId("lava")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.BURNING)
            .build();

    @NotNull
    public static final VanillaDamageType FLY_INTO_WALL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:fly_into_wall"))
            .messageId("flyIntoWall")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType LIGHTNING_BOLT = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:lightning_bolt"))
            .messageId("lightningBolt")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType PLAYER_ATTACK = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:player_attack"))
            .messageId("player")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType FREEZE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:freeze"))
            .messageId("freeze")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .effects(DamageEffects.FREEZING)
            .build();

    @NotNull
    public static final VanillaDamageType FALLING_ANVIL = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:falling_anvil"))
            .messageId("anvil")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType OUT_OF_WORLD = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:out_of_world"))
            .messageId("outOfWorld")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType MAGIC = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:magic"))
            .messageId("magic")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType SWEET_BERRY_BUSH = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:sweet_berry_bush"))
            .messageId("sweetBerryBush")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.POKING)
            .build();

    @NotNull
    public static final VanillaDamageType FIREWORKS = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:fireworks"))
            .messageId("fireworks")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType EXPLOSION = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:explosion"))
            .messageId("explosion")
            .scaling(DamageScaling.ALWAYS)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType BAD_RESPAWN_POINT = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:bad_respawn_point"))
            .messageId("badRespawnPoint")
            .scaling(DamageScaling.ALWAYS)
            .exhaustion(0.1f)
            .deathMessageType(DeathMessageType.INTENTIONAL_GAME_DESIGN)
            .build();

    @NotNull
    public static final VanillaDamageType STALAGMITE = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:stalagmite"))
            .messageId("stalagmite")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType THORNS = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:thorns"))
            .messageId("thorns")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .effects(DamageEffects.THORNS)
            .build();

    @NotNull
    public static final VanillaDamageType INDIRECT_MAGIC = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:indirect_magic"))
            .messageId("indirectMagic")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType CRAMMING = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:cramming"))
            .messageId("cramming")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    @NotNull
    public static final VanillaDamageType CACTUS = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:cactus"))
            .messageId("cactus")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.1f)
            .build();

    @NotNull
    public static final VanillaDamageType GENERIC = VanillaDamageType.builder()
            .name(NamespaceID.from("minecraft:generic"))
            .messageId("generic")
            .scaling(DamageScaling.WHEN_CAUSED_BY_LIVING_NON_PLAYER)
            .exhaustion(0.0f)
            .build();

    public static final List<VanillaDamageType> VALUES = Arrays.asList(
            WITHER,
            SONIC_BOOM,
            WITHER_SKULL,
            DRY_OUT,
            TRIDENT,
            ON_FIRE,
            FALL,
            MOB_ATTACK,
            MOB_PROJECTILE,
            THROWN,
            FALLING_STALACTITE,
            FIREBALL,
            FALLING_BLOCK,
            PLAYER_EXPLOSION,
            STING,
            UNATTRIBUTED_FIREBALL,
            IN_WALL,
            IN_FIRE,
            ARROW,
            HOT_FLOOR,
            DROWN,
            STARVE,
            DRAGON_BREATH,
            MOB_ATTACK_NO_AGGRO,
            LAVA,
            FLY_INTO_WALL,
            LIGHTNING_BOLT,
            PLAYER_ATTACK,
            FREEZE,
            FALLING_ANVIL,
            OUT_OF_WORLD,
            MAGIC,
            SWEET_BERRY_BUSH,
            FIREWORKS,
            EXPLOSION,
            BAD_RESPAWN_POINT,
            STALAGMITE,
            THORNS,
            INDIRECT_MAGIC,
            CRAMMING,
            CACTUS,
            GENERIC
    );

    private VanillaDamageTypes() {
    }
}
